title: Simon Nordberg
description: ""
baseurl: ""
url: "https://simonnordberg.com"

twitter:
  username: simonnordberg
  card: summary
logo: /assets/avatar.jpg
social:
  name: Simon Nordberg
  links:
    - https://twitter.com/simonnordberg
author:
  twitter: simonnordberg

# Permalink structure for blog posts (root-level with title slug)
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/avatar.jpg
  - scope:
      path: ""
      type: "posts"
    values:
      layout: article